server: 
  port: 4001
spring:
  application:
    name: feign-consumer
  profiles: 
    active: "@activatedProperties@"
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/  